### PR TITLE
Adding function hasAnyRole

### PR DESCRIPTION
**Pull request by brunoneve**
You can check if user has a role.
using hasAnyRole([ 'admin', 'manager'])

### CODE REVIEW

**Comment by brunoneve** [comment]
using hasRole method ('admin') or hasRole ([ 'admin', 'manager']);

**Comment by mikemclin** [comment]
Not exactly what I was saying, but I also like the idea of multi-purposing a single method like you implemented.  Thanks.  Merging.

**Comment by mikemclin** [comment]
Made some tweaks to functionality.  Figured we're already using the **any** verb with `canAny` and wanted that to carry over to **roles**.  So, I added `hasAnyRole`.  I left the `hasRole` parameter as either a string or array, but now if an array is given we are checking that every role exists.  You can read the docs for further info - https://github.com/mikemclin/angular-acl#aclservicehasrolerole.

Also, this has been tagged, so you should be able to start using this in your project.  Thanks again.

**Comment by brunoneve** [comment]
Very god. Thx

**Pull request merged**
